"""model cleanups

Revision ID: cd59e4f30825
Revises: 9d1ef721647a
Create Date: 2024-01-26 02:09:09.719390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd59e4f30825'
down_revision = '9d1ef721647a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('county', sa.String(), nullable=True))
        batch_op.drop_column('county_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('county_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('county')

    # ### end Alembic commands ###
