"""initial model

Revision ID: d524380e7b3c
Revises: 
Create Date: 2024-03-07 20:20:50.805043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd524380e7b3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('election_deadlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voter_registration_deadline', sa.Date(), nullable=True),
    sa.Column('mail_in_ballot_deployment_date', sa.Date(), nullable=True),
    sa.Column('mail_in_ballot_return_opening', sa.Date(), nullable=True),
    sa.Column('mail_in_ballot_return_deadline', sa.Date(), nullable=True),
    sa.Column('mail_in_ballot_postmark_deadline', sa.Date(), nullable=True),
    sa.Column('early_in_person_voting_opening', sa.Date(), nullable=True),
    sa.Column('early_in_person_voting_deadline', sa.Date(), nullable=True),
    sa.Column('in_person_election_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('overview', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('voting_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('early_voting', sa.Boolean(), nullable=True),
    sa.Column('vote_by_mail', sa.Boolean(), nullable=True),
    sa.Column('in_person_voting', sa.Boolean(), nullable=True),
    sa.Column('mobile_voting', sa.Boolean(), nullable=True),
    sa.Column('online_voting', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('deadlines_id', sa.Integer(), nullable=True),
    sa.Column('options_id', sa.Integer(), nullable=True),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('election_type', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['deadlines_id'], ['election_deadlines.id'], name=op.f('fk_elections_deadlines_id_election_deadlines')),
    sa.ForeignKeyConstraint(['options_id'], ['voting_options.id'], name=op.f('fk_elections_options_id_voting_options')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_states_country_id_countries')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('voters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_photo', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('street_line1', sa.String(), nullable=True),
    sa.Column('street_line2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('race', sa.String(), nullable=True),
    sa.Column('ethnicity', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('veteran_status', sa.String(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('voter_registration_status', sa.String(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_voters_party_id_parties')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_voters_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('counties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], name=op.f('fk_counties_state_id_states')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], name=op.f('fk_cities_county_id_counties')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cities')
    op.drop_table('counties')
    op.drop_table('voters')
    op.drop_table('states')
    op.drop_table('elections')
    op.drop_table('voting_options')
    op.drop_table('users')
    op.drop_table('parties')
    op.drop_table('election_deadlines')
    op.drop_table('countries')
    # ### end Alembic commands ###
